stages:
  - build

#variables:
#  PROJECT_DEPLOY_ENTRYPOINT: "build:group"
#  GIT_STRATEGY: fetch

003-build-npm-extern:
  stage: build
  image:
    name: scm.kfw.kfwgruppe.net:443/global/templates/baseimages/ubi9-nodejs20:0.0.4-RELEASE
    entrypoint: [""]
  needs:
    - job: generate-config-pipe2.0
      artifacts: true
      optional: true
    - job: 0000-compliance_init
      optional: true
    - job: 000-compliance_init_RC
      optional: true
  script:
    #- !reference [.npm-auth, script]
    # das image hat die kfw zertifikate nicht
    - auth=$(echo -n "${NEXUS_LIB_USER}:${NEXUS_LIB_PASSWORD}" | openssl base64)
    - npm config set registry=https://${ENV_URL}/${NEXUS_ENV}3/repository/kfw-npm-repositories/
    - npm config set ${NEXUS_NPM_PULL_URL}/:_auth=$auth

    - npm config set strict-ssl false
    - npm i
  artifacts:
    untracked: true
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: on_success
    - if: $CI_COMMIT_REF_NAME == "RC" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: on_success
    - if: $CI_COMMIT_REF_NAME == "DEV" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: on_success
    - if: $CI_COMMIT_REF_NAME =~ "/^feature.*$/" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: on_success
